<section class="min-h-[calc(100vh-4rem)] bg-[#f3f4f6] text-slate-950">
    <div class="mx-auto max-w-[1500px] px-4 py-5 sm:px-6 lg:px-8">
        <div class="mb-4 rounded-lg border border-slate-200 bg-white px-4 py-4 shadow-sm">
            <h1 class="text-lg font-bold">Financial Management</h1>
            <p class="mt-1 text-sm text-slate-500">Chi hien thi cac account tai chinh ban duoc cap quyen.</p>
        </div>

        <div class="mb-4 grid gap-3 rounded-lg border border-slate-200 bg-white p-4 shadow-sm md:grid-cols-4">
            <select wire:model.live="platform" class="h-10 rounded-md border-slate-300 text-sm"><option value="">All platforms</option>@foreach ($accounts->pluck('platform')->unique()->sort() as $item)<option value="{{ $item }}">{{ ucfirst($item) }}</option>@endforeach</select>
            <select wire:model.live="accountId" class="h-10 rounded-md border-slate-300 text-sm"><option value="">All accounts</option>@foreach ($accounts as $account)<option value="{{ $account->id }}">{{ $account->name }} ({{ $account->currency }})</option>@endforeach</select>
            <select wire:model.live="type" class="h-10 rounded-md border-slate-300 text-sm"><option value="">All transaction types</option><option value="revenue">Revenue</option><option value="fulfillment">Fulfillment</option><option value="expense">Expense</option></select>
            <input wire:model.live.debounce.400ms="search" type="search" placeholder="Search transaction, category, reference..." class="h-10 rounded-md border-slate-300 text-sm">
        </div>

        <div class="mb-4 grid gap-3 md:grid-cols-2 xl:grid-cols-4">
            @foreach ($summaryByCurrency as $currency => $summary)
                <div class="rounded-lg border border-slate-200 bg-white p-4 shadow-sm"><p class="text-xs font-bold uppercase tracking-wide text-slate-400">{{ $currency }} remaining balance</p><p class="mt-2 text-2xl font-bold {{ $summary['balance'] < 0 ? 'text-rose-600' : 'text-emerald-600' }}">{{ number_format($summary['balance'], 2) }}</p><div class="mt-3 grid grid-cols-3 gap-2 text-xs"><div><p class="text-slate-400">Received</p><p class="font-semibold">{{ number_format($summary['received'], 2) }}</p></div><div><p class="text-slate-400">Fulfill</p><p class="font-semibold">{{ number_format($summary['fulfillment'], 2) }}</p></div><div><p class="text-slate-400">Expense</p><p class="font-semibold">{{ number_format($summary['expenses'], 2) }}</p></div></div></div>
            @endforeach
        </div>

        <div class="mb-4 overflow-hidden rounded-lg border border-slate-200 bg-white shadow-sm">
            <div class="border-b border-slate-200 px-4 py-3"><h2 class="font-bold">Financial accounts</h2></div>
            <div class="overflow-x-auto"><table class="min-w-full text-sm"><thead class="bg-slate-50 text-left text-xs uppercase tracking-wide text-slate-500"><tr><th class="px-4 py-3">Account</th><th class="px-4 py-3">Platform</th><th class="px-4 py-3">Currency</th><th class="px-4 py-3 text-right">Action</th></tr></thead><tbody class="divide-y divide-slate-100">@foreach ($accounts as $account)<tr><td class="px-4 py-3"><p class="font-semibold">{{ $account->name }}</p><p class="text-xs text-slate-400">{{ $account->code }}</p></td><td class="px-4 py-3 capitalize">{{ $account->platform }}</td><td class="px-4 py-3">{{ $account->currency }}</td><td class="px-4 py-3 text-right">@if (in_array($account->id, $canAddAccountIds, true))<button wire:click="openTransactionForm(null, {{ $account->id }})" class="text-xs font-semibold text-emerald-700">Add transaction</button>@else<span class="text-xs text-slate-400">View only</span>@endif</td></tr>@endforeach</tbody></table></div>
        </div>
        <div class="overflow-hidden rounded-lg border border-slate-200 bg-white shadow-sm">
            <div class="flex items-center justify-between border-b border-slate-200 px-4 py-3"><div><h2 class="font-bold">Transactions</h2><p class="mt-0.5 text-xs text-slate-500">Balance duoc tinh tu giao dich chua bi xoa.</p></div></div>
            <div class="overflow-x-auto"><table class="min-w-full text-sm"><thead class="bg-slate-50 text-left text-xs uppercase tracking-wide text-slate-500"><tr><th class="px-4 py-3">Date</th><th class="px-4 py-3">Transaction</th><th class="px-4 py-3">Account</th><th class="px-4 py-3">Type</th><th class="px-4 py-3">Category</th><th class="px-4 py-3 text-right">Amount</th><th class="px-4 py-3 text-right">Actions</th></tr></thead><tbody class="divide-y divide-slate-100">
                @forelse ($transactions as $transaction)
                    <tr><td class="px-4 py-3">{{ $transaction->transaction_date?->format('Y-m-d') }}</td><td class="px-4 py-3"><p class="font-semibold">{{ $transaction->transaction_number }}</p><p class="max-w-xs truncate text-xs text-slate-400">{{ $transaction->reference ?: $transaction->description }}</p></td><td class="px-4 py-3">{{ $transaction->account->name }}<p class="text-xs text-slate-400">{{ $transaction->account->currency }}</p></td><td class="px-4 py-3 capitalize">{{ $transaction->type }}</td><td class="px-4 py-3">{{ $transaction->category }}</td><td class="px-4 py-3 text-right font-semibold">{{ number_format((float) $transaction->amount, 2) }}</td><td class="px-4 py-3 text-right">@if (in_array($transaction->financial_account_id, $canEditAccountIds, true))<button wire:click="openTransactionForm({{ $transaction->id }})" class="mr-2 text-xs font-semibold text-cyan-700">Edit</button>@endif @if (in_array($transaction->financial_account_id, $canDeleteAccountIds, true))<button wire:confirm="Xoa giao dich nay? Balance se tu tinh lai." wire:click="deleteTransaction({{ $transaction->id }})" class="text-xs font-semibold text-rose-600">Delete</button>@endif</td></tr>
                @empty
                    <tr><td colspan="7" class="px-4 py-10 text-center text-slate-400">Chua co giao dich nao.</td></tr>
                @endforelse
            </tbody></table></div>
            <x-offorest.pagination :paginator="$transactions" class="border-t border-slate-200" />
        </div>
    </div>

    @if ($isTransactionModalOpen)
        <div class="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/40 p-4" wire:click.self="closeTransactionForm"><div class="w-full max-w-xl rounded-xl bg-white p-5 shadow-2xl"><div class="mb-4 flex items-center justify-between"><div><h2 class="text-lg font-bold">{{ $transactionId ? 'Edit transaction' : 'Add transaction' }}</h2><p class="text-sm text-slate-500">Chi hien cac account ban co quyen thao tac.</p></div><button wire:click="closeTransactionForm" class="text-slate-400">X</button></div><form wire:submit="saveTransaction" class="space-y-4"><label class="block text-sm font-semibold">Account<select wire:model="financialAccountId" class="mt-1 block w-full rounded-md border-slate-300"><option value="">Select account</option>@foreach ($accounts as $account)@if (in_array($account->id, $canAddAccountIds, true) || ($transactionId && in_array($account->id, $canEditAccountIds, true)))<option value="{{ $account->id }}">{{ $account->name }} - {{ $account->currency }}</option>@endif@endforeach</select>@error('financialAccountId')<p class="mt-1 text-xs text-rose-600">{{ $message }}</p>@enderror</label><div class="grid gap-3 md:grid-cols-2"><label class="text-sm font-semibold">Date<input wire:model="transactionDate" type="date" class="mt-1 block w-full rounded-md border-slate-300"></label><label class="text-sm font-semibold">Type<select wire:model.live="transactionType" class="mt-1 block w-full rounded-md border-slate-300"><option value="revenue">Revenue</option><option value="fulfillment">Fulfillment</option><option value="expense">Expense</option></select></label><label class="text-sm font-semibold">Category<input wire:model="category" class="mt-1 block w-full rounded-md border-slate-300"></label><label class="text-sm font-semibold">Amount<input wire:model="amount" type="number" min="0.01" step="0.01" class="mt-1 block w-full rounded-md border-slate-300"></label></div><label class="block text-sm font-semibold">Reference<input wire:model="reference" class="mt-1 block w-full rounded-md border-slate-300"></label><label class="block text-sm font-semibold">Description<textarea wire:model="description" rows="3" class="mt-1 block w-full rounded-md border-slate-300"></textarea></label><label class="block text-sm font-semibold">Note<textarea wire:model="note" rows="3" class="mt-1 block w-full rounded-md border-slate-300" placeholder="Internal note (optional)"></textarea></label><div class="flex justify-end gap-2"><button type="button" wire:click="closeTransactionForm" class="rounded-md border px-4 py-2 text-sm font-semibold">Cancel</button><button type="submit" class="rounded-md bg-emerald-600 px-4 py-2 text-sm font-bold text-white">Save transaction</button></div></form></div></div>
    @endif
</section>
