<section class="min-h-[calc(100vh-4rem)] bg-slate-50 text-slate-900">
    <div class="mx-auto max-w-[1600px] space-y-4 px-4 py-5 sm:px-6 lg:px-8">
        <div class="flex flex-wrap items-end justify-between gap-3">
            <div><h1 class="text-2xl font-bold tracking-tight">Financial Management</h1><p class="text-sm text-slate-500">Overview</p></div>
            <div class="flex gap-2"><button wire:click="$dispatch('openModal', { component: 'modals.admin.financial-transaction-form' })" class="rounded-md bg-emerald-600 px-3 py-2 text-xs font-bold text-white">Add transaction</button><button wire:click="$dispatch('openModal', { component: 'modals.admin.financial-account-form' })" class="rounded-md bg-cyan-600 px-3 py-2 text-xs font-bold text-white">Add account</button></div>
        </div>
        <div class="grid gap-3 rounded-xl border border-slate-200 bg-white p-4 shadow-sm md:grid-cols-2 xl:grid-cols-7">
            <label class="text-xs font-bold text-slate-500">Platform<select wire:model.live="platform" class="mt-1 h-10 w-full rounded-md border-slate-300 text-sm"><option value="">All Platforms</option>@foreach ($platformOptions as $option)<option value="{{ $option }}">{{ ucfirst($option) }}</option>@endforeach</select></label>
            <div x-data="{ open: false, search: '' }" class="relative text-xs font-bold text-slate-500">
                <span>Accounts</span>
                <button type="button" @click="open = !open" class="mt-1 flex h-10 w-full items-center justify-between rounded-md border border-slate-300 bg-white px-3 text-left text-sm font-normal text-slate-700">
                    <span>{{ count($selectedAccountIds) ? count($selectedAccountIds).' accounts selected' : 'All accounts' }}</span><span class="text-slate-400">⌄</span>
                </button>
                <div x-show="open" x-cloak @click.outside="open = false" class="absolute left-0 right-0 z-30 mt-1 max-h-80 overflow-y-auto rounded-md border border-slate-200 bg-white p-2 font-normal shadow-xl">
                    <input x-model="search" type="search" placeholder="Search accounts..." class="mb-2 h-9 w-full rounded border-slate-300 text-sm">
                    <label class="flex items-center gap-2 border-b border-slate-100 px-2 py-2 text-sm font-semibold"><input type="checkbox" wire:click="toggleAllAccounts" @checked(count($selectedAccountIds) === $accounts->count())> Select All</label>
                    @foreach ($accounts->groupBy('platform') as $platformName => $platformAccounts)
                        <p class="px-2 pb-1 pt-3 text-[10px] font-bold uppercase tracking-wider text-slate-400">{{ $platformName }}</p>
                        @foreach ($platformAccounts as $account)
                            <label x-show="'{{ strtolower($account->name) }}'.includes(search.toLowerCase())" class="flex cursor-pointer items-center gap-2 rounded px-2 py-1.5 text-sm hover:bg-slate-50"><input type="checkbox" wire:model.live="selectedAccountIds" value="{{ $account->id }}"><span>{{ $account->name }}</span></label>
                        @endforeach
                    @endforeach
                    <div class="mt-2 flex justify-between border-t border-slate-100 px-2 pt-2 text-xs"><span class="font-semibold text-cyan-700">{{ count($selectedAccountIds) }} selected</span><button type="button" wire:click="clearSelectedAccounts" class="font-semibold text-cyan-700">Clear</button></div>
                </div>
            </div>
            <label class="text-xs font-bold text-slate-500">Year<select wire:model.live="selectedYear" class="mt-1 h-10 w-full rounded-md border-slate-300 text-sm"><option value="">All years</option>@foreach ($yearOptions as $year)<option value="{{ $year }}">{{ $year }}</option>@endforeach</select></label>
            <label class="text-xs font-bold text-slate-500">Date range<select wire:model.live="datePreset" class="mt-1 h-10 w-full rounded-md border-slate-300 text-sm"><option value="today">Today</option><option value="yesterday">Yesterday</option><option value="this_week">This Week</option><option value="last_week">Last Week</option><option value="this_month">This Month</option><option value="last_month">Last Month</option><option value="this_quarter">This Quarter</option><option value="this_year">This Year</option><option value="last_year">Last Year</option><option value="custom">Custom Range</option></select></label>
            <label class="text-xs font-bold text-slate-500">Start date<input wire:model.live="startDate" type="date" class="mt-1 h-10 w-full rounded-md border-slate-300 text-sm"></label>
            <label class="text-xs font-bold text-slate-500">End date<input wire:model.live="endDate" type="date" class="mt-1 h-10 w-full rounded-md border-slate-300 text-sm"></label>
            <label class="text-xs font-bold text-slate-500">Group by<select wire:model.live="groupBy" class="mt-1 h-10 w-full rounded-md border-slate-300 text-sm"><option value="day">Day</option><option value="week">Week</option><option value="month">Month</option><option value="quarter">Quarter</option><option value="year">Year</option></select></label>
            <div class="flex items-end"><button wire:click="resetFilters" class="h-10 w-full rounded-md border border-slate-300 bg-white px-3 text-sm font-semibold">Reset</button></div>
        </div>
        <div class="grid gap-3 md:grid-cols-2 xl:grid-cols-4">
            @foreach ([['Total Received','received','emerald'],['Total Fulfillment','fulfillment','rose'],['Total Expenses','expenses','rose'],['Balance','balance','blue']] as [$label,$key,$color])
                <div class="rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><p class="text-xs font-semibold text-slate-500">{{ $label }}</p><p class="mt-2 text-2xl font-bold text-{{ $color }}-600">{{ number_format($dashboardTotals[$key], 2) }}</p><p class="mt-1 text-xs text-slate-400">Selected accounts · {{ count($selectedAccounts) }}</p></div>
            @endforeach
        </div>
        <div class="grid gap-4 xl:grid-cols-[minmax(0,1fr)_280px]">
            <div class="space-y-4">
                <div class="rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><div class="mb-3 flex items-center justify-between"><h2 class="font-bold">Balance Over Time (Monthly)</h2><span class="text-xs text-slate-400">{{ $startDate }} → {{ $endDate }}</span></div><div class="grid h-44 grid-cols-12 items-end gap-2 border-b border-l border-slate-200 px-2 pb-2">@foreach ($monthlySummary as $month)<div class="group flex h-full flex-col justify-end"><div class="rounded-t bg-cyan-500/80" style="height: {{ min(100, max(4, ($month['totals']['balance'] / max(1, $dashboardTotals['received'])) * 100)) }}%"></div><span class="mt-1 text-center text-[10px] text-slate-400">{{ $month['label'] }}</span></div>@endforeach</div></div>
                <div class="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"><div class="border-b border-slate-200 px-4 py-3"><h2 class="font-bold">Monthly Financial Summary</h2><p class="mt-1 text-xs text-slate-400">Click a period to see its daily details.</p></div><div class="overflow-x-auto"><table class="min-w-full text-xs"><thead class="bg-slate-50 text-left text-slate-500"><tr><th class="px-3 py-2">Period</th><th class="px-3 py-2">Received</th><th class="px-3 py-2">Fulfillment</th><th class="px-3 py-2">Expenses</th><th class="px-3 py-2">Balance</th></tr></thead><tbody class="divide-y divide-slate-100">@forelse ($monthlySummary as $month)<tr wire:click="toggleSummaryPeriod('{{ $month['key'] }}')" class="cursor-pointer hover:bg-cyan-50"><td class="px-3 py-2 font-semibold"><span class="mr-1 text-cyan-700">{{ in_array($month['key'], $expandedSummaryPeriods, true) ? '−' : '+' }}</span>{{ $month['label'] }}</td><td class="px-3 py-2 text-emerald-700">{{ number_format($month['totals']['received'],2) }}</td><td class="px-3 py-2">{{ number_format($month['totals']['fulfillment'],2) }}</td><td class="px-3 py-2 text-rose-600">{{ number_format($month['totals']['expenses'],2) }}</td><td class="px-3 py-2 font-bold text-cyan-700">{{ number_format($month['totals']['balance'],2) }}</td></tr>@if (in_array($month['key'], $expandedSummaryPeriods, true))<tr><td colspan="5" class="bg-slate-50 p-3"><div class="rounded-md border border-slate-200 bg-white"><div class="border-b border-slate-100 px-3 py-2 text-xs font-bold text-slate-600">Daily details</div><table class="min-w-full text-xs"><thead class="text-left text-slate-400"><tr><th class="px-3 py-2">Date</th><th class="px-3 py-2">Transactions</th><th class="px-3 py-2">Received</th><th class="px-3 py-2">Fulfillment</th><th class="px-3 py-2">Expenses</th><th class="px-3 py-2">Balance</th></tr></thead><tbody class="divide-y divide-slate-100">@foreach (($dailySummaryByPeriod[$month['key']] ?? []) as $day)<tr><td class="px-3 py-2 font-semibold">{{ \Illuminate\Support\Carbon::parse($day['date'])->format('d M Y') }}</td><td class="px-3 py-2">{{ $day['count'] }}</td><td class="px-3 py-2 text-emerald-700">{{ number_format($day['totals']['received'],2) }}</td><td class="px-3 py-2">{{ number_format($day['totals']['fulfillment'],2) }}</td><td class="px-3 py-2 text-rose-600">{{ number_format($day['totals']['expenses'],2) }}</td><td class="px-3 py-2 font-bold text-cyan-700">{{ number_format($day['totals']['balance'],2) }}</td></tr>@endforeach</tbody></table></div></td></tr>@endif @empty<tr><td colspan="5" class="px-3 py-6 text-center text-slate-400">No financial data for this filter.</td></tr>@endforelse</tbody></table></div></div>
            </div>
            <aside class="rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><h2 class="font-bold">Recent Transactions</h2><div class="mt-3 divide-y divide-slate-100">@forelse ($recentTransactions as $transaction)<div class="py-3"><p class="text-sm font-semibold">{{ $transaction->category }}</p><p class="text-xs text-slate-400">{{ $transaction->transaction_date?->format('d/m/Y') }} · {{ $transaction->account?->name }}</p><p class="mt-1 text-right text-sm font-bold {{ $transaction->type === 'revenue' ? 'text-emerald-600' : 'text-rose-600' }}">{{ $transaction->type === 'revenue' ? '+' : '-' }}{{ number_format($transaction->amount,2) }}</p></div>@empty<p class="py-6 text-sm text-slate-400">No transactions.</p>@endforelse</div></aside>
        </div>
        <div class="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"><div class="border-b border-slate-200 px-4 py-3"><h2 class="font-bold">Transactions</h2></div><div class="overflow-x-auto"><table class="min-w-full text-sm"><thead class="bg-slate-50 text-left text-xs text-slate-500"><tr><th class="px-4 py-3">Date</th><th class="px-4 py-3">Transaction</th><th class="px-4 py-3">Account</th><th class="px-4 py-3">Type</th><th class="px-4 py-3 text-right">Amount</th><th class="px-4 py-3 text-right">Actions</th></tr></thead><tbody class="divide-y divide-slate-100">@forelse ($transactions as $transaction)<tr><td class="px-4 py-3">{{ $transaction->transaction_date?->format('d/m/Y') }}</td><td class="px-4 py-3"><b>{{ $transaction->transaction_number }}</b><p class="text-xs text-slate-400">{{ $transaction->category }}</p></td><td class="px-4 py-3">{{ $transaction->account?->name }}</td><td class="px-4 py-3 capitalize">{{ $transaction->type }}</td><td class="px-4 py-3 text-right font-semibold">{{ number_format($transaction->amount,2) }}</td><td class="px-4 py-3 text-right"><button wire:click="$dispatch('openModal', { component: 'modals.admin.financial-transaction-form', arguments: { transactionId: {{ $transaction->id }} } })" class="mr-2 text-xs font-semibold text-cyan-700">Edit</button><button wire:click="deleteTransaction({{ $transaction->id }})" wire:confirm="Delete transaction?" class="text-xs font-semibold text-rose-600">Delete</button></td></tr>@empty<tr><td colspan="6" class="px-4 py-8 text-center text-slate-400">No transactions.</td></tr>@endforelse</tbody></table></div><x-offorest.pagination :paginator="$transactions" class="border-t border-slate-200" /></div>
    </div>
    <livewire:modals.admin.financial-account-form /><livewire:modals.admin.financial-transaction-form />
</section>
