[program:xlap-suncatcher-pipeline]
process_name=%(program_name)s_%(process_num)02d
directory=/www/wwwroot/xlap.tech
command=/www/server/php/83/bin/php artisan queue:work database --queue=suncatcher-pipeline --sleep=1 --tries=1 --timeout=3600 --backoff=10 --memory=512
numprocs=2
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www
redirect_stderr=true
stdout_logfile=/www/wwwroot/xlap.tech/storage/logs/suncatcher-pipeline.log

[program:xlap-suncatcher-priority]
process_name=%(program_name)s_%(process_num)02d
directory=/www/wwwroot/xlap.tech
command=/www/server/php/83/bin/php artisan queue:work database --queue=suncatcher-priority --sleep=1 --tries=1 --timeout=3600 --backoff=10 --memory=512
numprocs=1
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www
redirect_stderr=true
stdout_logfile=/www/wwwroot/xlap.tech/storage/logs/suncatcher-priority.log
