[program:xlap-suncatcher-pipeline]
process_name=%(program_name)s_%(process_num)02d
directory=/www/wwwroot/xlap.tech
command=/www/server/php/83/bin/php artisan queue:work database --queue=suncatcher-priority,suncatcher-pipeline --sleep=1 --tries=1 --timeout=3600 --backoff=10 --memory=512
numprocs=5
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www
redirect_stderr=true
stdout_logfile=/www/wwwroot/xlap.tech/storage/logs/suncatcher-workers.log

[program:xlap-ornament-amazon-two-pipeline]
process_name=%(program_name)s_%(process_num)02d
directory=/www/wwwroot/xlap.tech
command=/www/server/php/83/bin/php artisan queue:work database --queue=ornament-priority,ornament-pipeline --sleep=1 --tries=1 --timeout=3600 --backoff=10 --memory=512
numprocs=5
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www
redirect_stderr=true
stdout_logfile=/www/wwwroot/xlap.tech/storage/logs/ornament-amazon-two-workers.log

[program:xlap-marketplace-listing-daemon]
process_name=%(program_name)s
directory=/www/wwwroot/xlap.tech
command=/www/server/php/83/bin/php artisan offorest:generate-listing-metadata --daemon --limit=1 --idle-sleep=2
numprocs=1
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www
redirect_stderr=true
stdout_logfile=/www/wwwroot/xlap.tech/storage/logs/marketplace-listing-daemon.log

[program:xlap-drive-upload-daemon]
process_name=%(program_name)s
directory=/www/wwwroot/xlap.tech
command=/www/server/php/83/bin/php artisan offorest:upload-approved-images-to-drive --daemon --idle-sleep=2
numprocs=1
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www
redirect_stderr=true
stdout_logfile=/www/wwwroot/xlap.tech/storage/logs/drive-upload-daemon.log
